name: Dumb Money Summary Bot
on:
  schedule:
    - cron: '0 */3 * * *' # Runs every 3 hours
  workflow_dispatch:      # Allows you to click a button to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Allows GitHub to update last_video.txt
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run logic
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WHATSAPP_PHONE: ${{ secrets.WHATSAPP_PHONE }}
          WHATSAPP_KEY: ${{ secrets.WHATSAPP_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python main.py
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add last_video.txt
          git commit -m "Update last video" || exit 0
          git push
